export const SAMPLE_BOOKINGS = {
  "data": [
    {
      "id": 2,
      "user_id": 2,
      "business_id": 1,
      "service_id": 1,
      "status": "CREATED",
      "schedule_time": "2024-09-03T10:00:00",
      "number_of_adults": 2,
      "number_of_children": 0,
      "additional_info": "Ажлын уулзалт",
      "phone": 90002497,
      "is_arrived": false
    },
    {
      "id": 1,
      "user_id": 2,
      "business_id": 1,
      "service_id": 1,
      "status": "CREATED",
      "schedule_time": "2024-09-05T11:00:00",
      "number_of_adults": 2,
      "number_of_children": 0,
      "additional_info": "Гэр бүлийн хоол",
      "phone": 90002497,
      "is_arrived": false
    },
    {
      "id": 3,
      "user_id": 1,
      "business_id": 1,
      "service_id": 1,
      "status": "CREATED",
      "schedule_time": "2024-09-18T11:00:00",
      "number_of_adults": 1,
      "number_of_children": 1,
      "additional_info": "Хүүхдийн сандалтай",
      "phone": 85586669,
      "is_arrived": false
    },
    {
      "id": 4,
      "user_id": 1,
      "business_id": 1,
      "service_id": 1,
      "status": "CREATED",
      "schedule_time": "2024-09-18T11:00:00",
      "number_of_adults": 1,
      "number_of_children": 1,
      "additional_info": "Төрсөн өдөр",
      "phone": 85586669,
      "is_arrived": false
    },
    {
      "id": 8,
      "user_id": 1,
      "business_id": 1,
      "service_id": 1,
      "status": "CREATED",
      "schedule_time": "2024-10-23T10:00:00",
      "number_of_adults": 2,
      "number_of_children": 4,
      "additional_info": "Хүүхэдтэй",
      "phone": 88087779,
      "is_arrived": false
    },
    {
      "id": 9,
      "user_id": 1,
      "business_id": 1,
      "service_id": 1,
      "status": "CREATED",
      "schedule_time": "2024-10-26T19:00:00",
      "number_of_adults": 10,
      "number_of_children": 2,
      "additional_info": "Компанийн арга хэмжээ",
      "phone": 80244882,
      "is_arrived": false
    },
    {
      "id": 10,
      "user_id": 1,
      "business_id": 1,
      "service_id": 1,
      "status": "CREATED",
      "schedule_time": "2024-10-30T13:20:00",
      "number_of_adults": 1,
      "number_of_children": 1,
      "additional_info": "Өдрийн хоол",
      "phone": 80244882,
      "is_arrived": false
    },
    {
      "id": 12,
      "user_id": 1,
      "business_id": 1,
      "service_id": 1,
      "status": "PENDING",
      "schedule_time": "2024-11-02T17:09:39",
      "number_of_adults": 1,
      "number_of_children": 0,
      "additional_info": "Оройн хоол",
      "phone": 80244882,
      "is_arrived": false
    },
    {
      "id": 13,
      "user_id": 1,
      "business_id": 1,
      "service_id": 1,
      "status": "PENDING",
      "schedule_time": "2024-11-02T17:19:34",
      "number_of_adults": 1,
      "number_of_children": 0,
      "additional_info": "Найзуудын уулзалт",
      "phone": 80244882,
      "is_arrived": false
    },
    {
      "id": 14,
      "user_id": 1,
      "business_id": 1,
      "service_id": 1,
      "status": "PENDING",
      "schedule_time": "2024-11-02T17:19:34",
      "number_of_adults": 1,
      "number_of_children": 0,
      "additional_info": "Гэр бүлийн хоол",
      "phone": 80244882,
      "is_arrived": false
    },
    {
      "id": 16,
      "user_id": 1,
      "business_id": 1,
      "service_id": 1,
      "status": "CANCELLED",
      "schedule_time": "2024-11-04T05:11:52",
      "number_of_adults": 1,
      "number_of_children": 0,
      "additional_info": "Цуцлагдсан",
      "phone": 10000000,
      "is_arrived": false
    },
    {
      "id": 17,
      "user_id": 1,
      "business_id": 1,
      "service_id": 1,
      "status": "PAID",
      "schedule_time": "2024-11-06T03:31:26",
      "number_of_adults": 1,
      "number_of_children": 0,
      "additional_info": "Урьдчилсан төлбөр хийсэн",
      "phone": 80244882,
      "is_arrived": false
    },
    {
      "id": 18,
      "user_id": 1,
      "business_id": 1,
      "service_id": 1,
      "status": "PAID",
      "schedule_time": "2024-11-06T03:31:26",
      "number_of_adults": 1,
      "number_of_children": 0,
      "additional_info": "VIP өрөө",
      "phone": 80244882,
      "is_arrived": false
    },
    {
      "id": 19,
      "user_id": 1,
      "business_id": 1,
      "service_id": 1,
      "status": "PAID",
      "schedule_time": "2024-11-06T03:31:26",
      "number_of_adults": 1,
      "number_of_children": 0,
      "additional_info": "Энгийн ширээ",
      "phone": 80244882,
      "is_arrived": false
    },
    {
      "id": 20,
      "user_id": 1,
      "business_id": 1,
      "service_id": 1,
      "status": "PAID",
      "schedule_time": "2024-11-06T03:31:26",
      "number_of_adults": 1,
      "number_of_children": 0,
      "additional_info": "Цонхны дэргэд",
      "phone": 80244882,
      "is_arrived": false
    },
    {
      "id": 21,
      "user_id": 1,
      "business_id": 1,
      "service_id": 1,
      "status": "PAID",
      "schedule_time": "2024-11-06T03:31:26",
      "number_of_adults": 1,
      "number_of_children": 0,
      "additional_info": "Тусгай хүсэлт",
      "phone": 80244882,
      "is_arrived": false
    },
    {
      "id": 22,
      "user_id": 1,
      "business_id": 1,
      "service_id": 1,
      "status": "PAID",
      "schedule_time": "2024-11-06T03:31:26",
      "number_of_adults": 1,
      "number_of_children": 0,
      "additional_info": "Халал хоол",
      "phone": 80244882,
      "is_arrived": false
    },
    {
      "id": 11,
      "user_id": 7,
      "business_id": 1,
      "service_id": 10,
      "status": "CREATED",
      "schedule_time": "2024-11-14T10:00:00",
      "number_of_adults": 2,
      "number_of_children": 2,
      "additional_info": "Гэр бүлийн хоол",
      "phone": 90002497,
      "is_arrived": false
    }
  ],
  "count": 18
};

export type Booking = typeof SAMPLE_BOOKINGS.data[0]; 